service: my-serverless-app

provider:
  name: aws
  runtime: python3.9

functions:
  webhook:
    handler: handler.webhook
    events:
      - httpApi:
          path: /webhook
          method: post


          provider:
    name: aws
    runtime: nodejs16.x
    iamRoleStatements:
        - Effect: Allow
          Action: "dynamodb:Scan"
          Resource: "*"
